"""empty message

Revision ID: 469f847a5f80
Revises: 28b7961b5c2a
Create Date: 2024-05-04 16:22:17.966197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469f847a5f80'
down_revision = '28b7961b5c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_image', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('zip', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('zip')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('user_image')

    # ### end Alembic commands ###
