"""empty message

Revision ID: 509c62576361
Revises: dfbd72dabd35
Create Date: 2024-05-24 07:55:59.502270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '509c62576361'
down_revision = 'dfbd72dabd35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('transaction_ibfk_2', type_='foreignkey')
        batch_op.drop_column('quantity')
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('quantity', mysql.TEXT(), nullable=False))
        batch_op.create_foreign_key('transaction_ibfk_2', 'user', ['seller_id'], ['user_id'])
        batch_op.drop_column('serial_number')

    # ### end Alembic commands ###
