"""empty message

Revision ID: 996f73765208
Revises: 4284c8de615d
Create Date: 2024-05-26 21:36:05.674555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '996f73765208'
down_revision = '4284c8de615d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('transaction_status',
               existing_type=mysql.ENUM('pending', 'canceled', 'completed'),
               type_=sa.Enum('pending', 'failed', 'completed'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('transaction_status',
               existing_type=sa.Enum('pending', 'failed', 'completed'),
               type_=mysql.ENUM('pending', 'canceled', 'completed'),
               existing_nullable=True)

    # ### end Alembic commands ###
