"""empty message

Revision ID: dfbd72dabd35
Revises: f1394b16d594
Create Date: 2024-05-21 23:59:53.016465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfbd72dabd35'
down_revision = 'f1394b16d594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending,confirmed'),
               type_=sa.Enum('pending', 'confirmed'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'confirmed'),
               type_=mysql.ENUM('pending,confirmed'),
               existing_nullable=True)

    # ### end Alembic commands ###
