"""empty message

Revision ID: 091d9b7590a2
Revises: 34c564a5df38
Create Date: 2024-05-13 14:42:40.044774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '091d9b7590a2'
down_revision = '34c564a5df38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transactiion_status', sa.Enum('pending,canceled,completed'), nullable=True))
        batch_op.drop_column('transactiion_ststus')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transactiion_ststus', mysql.ENUM('pending,canceled,completed'), nullable=True))
        batch_op.drop_column('transactiion_status')

    # ### end Alembic commands ###
