"""empty message

Revision ID: 12d7704ff624
Revises: d803f172a583
Create Date: 2024-05-24 09:43:25.403573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12d7704ff624'
down_revision = 'd803f172a583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_status', sa.Enum('pending,canceled,completed'), nullable=True))
        batch_op.drop_column('transactiion_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transactiion_status', mysql.ENUM('pending,canceled,completed'), nullable=True))
        batch_op.drop_column('transaction_status')

    # ### end Alembic commands ###
