"""empty message

Revision ID: 4284c8de615d
Revises: 5c83ce72cc11
Create Date: 2024-05-26 21:33:40.218769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4284c8de615d'
down_revision = '5c83ce72cc11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###
