"""empty message

Revision ID: 8661421f1fb5
Revises: 996f73765208
Create Date: 2024-05-26 23:16:53.878086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8661421f1fb5'
down_revision = '996f73765208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cat_image', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('cat_image')

    # ### end Alembic commands ###
